### ISSUE TITLE
For public key exchange, encourage Elliptic Curve Diffie Hellman Ephemeral keys, or ECDSA, rather than just RSA

### ISSUE THREAD

**Issue by marek-lach** [simplex-chat/simplexmq#206]
A _elliptic curve_ Diffie-Hellman _ephemeral_ key exchange encouraged in the protocol specification could be a good idea for more resilient security, because it's stronger than just _RSA_, while well supported by most programming languages, like [Rust](https://docs.rs/x25519-dalek/1.2.0/x25519_dalek/), C++, or [Go](https://pkg.go.dev/go.bryk.io/pkg/crypto/x25519), for example, already.

Jami is also planning to [replace RSA by elliptic curves](https://git.jami.net/savoirfairelinux/jami-project/-/issues/1307) now.

**Comment by epoberezkin** [comment]
@marek-lach for client-server SMP protocol we will switch to EC keys (specifically, Ed448/25519 for command signatures) in the next version (v0.5) - you can see the updated protocol spec in v5 branch.

For the end-to-end encryption we will be moving to double ratchet protocol, also with EC keys (Curve448/25519), but it won’t happen in v0.5, but it will happen in the next version, most likely at the same time as we have a mobile app for SimpleX Chat.

Are you interested in contributing maybe?
