### ISSUE TITLE
Error trying to get my link using /c in CLI when connected to my node.

### ISSUE THREAD

**Issue by dtuando** [simplex-chat/simplexmq#328]
smp agent error: BROKER {brokerErr = NETWORK}
 
exception: HandshakeFailed (Error_Protocol ("certificate rejected: [NameMismatch \"IPADDRESSREDACTED\"]",True,CertificateUnknown))

**Comment by epoberezkin** [comment]
The error most likely indicates that the hostname of the server does not match the hostname in the certificate - you should pass it via parameters when initialising the server.

Also, you should check that the fingerprint of the certificate you pass in the server address is correct.

**Comment by dtuando** [comment]
Thank you for the quick response. I'll try passing the parameters when running the server that seems like it would be the issue

**Comment by mika-nl** [comment]
You can do smp-server init --IP host.name.bla

**Comment by epoberezkin** [comment]
closing
