### ISSUE TITLE
Unable to build docker images on Apple Silicon [to build ARM image for start9 marketplace]

### ISSUE THREAD

**Issue by shyfire-131** [simplex-chat/simplexmq#678]
Hi! I'm busy exploring the idea of packaging SimpleXMQ for the [start9](https://start9.com) marketplace (will run in the beta marketplace for a while at first).

One of the things that is required is an ARM docker image. I've been able to update the [build.Dockerfile](https://github.com/simplex-chat/simplexmq/blob/stable/build.Dockerfile), however the updates are pretty substantial. 

I'd like to get this merged in or supported however, since without it keeping the start9 package in sync with upstream changes of smp-server is going to be challenging.

What's the best way to get feedback from you guys on this - shall I open a PR with my modified `build.Dockerfile` and a description of the changes?

**Comment by epoberezkin** [comment]
Great - thank you!

cc @shumvgolove

**Comment by shumvgolove** [comment]
Issue is resolved.
