### ISSUE TITLE
Add IPv6 support

### ISSUE THREAD

**Issue by Mynacol** [simplex-chat/simplexmq#703]
Currently, none of the official relay servers (`smp4.simplex.im` - `smp10.simplex.im`) have a AAAA DNS record, making them only reachable via IPv4. Adding IPv6 connectivity helps keeping long-term connections (e.g. from Android clients) alive. This allows to reduce the frequency of keepalive messages and in turn helps conserving battery space.

To deploy IPv6, the server code needs to be able to handle IP addresses in IPv6 format. Then IPv6 has to be added to the servers and announced with AAAA DNS records.
The clients may also need software changes to actually use IPv6.

**Comment by dvn0** [comment]
This is done, right?
