### ISSUE TITLE
Image on Docker Hub not atomatically updated

### ISSUE THREAD

**Issue by samsapti** [simplex-chat/simplexmq#732]
The Docker image that's available on Docker Hub is currently on version 4.3.1, i.e. 3 versions behind. Do you guys have plans to keep it up to date, or is the intention that SMP server operators should build the Docker image themselves?

If it's of any help, I can make a PR with a GitHub Actions workflow to automatically build and push a Docker image on every release. Let me know what you think.

**Comment by samsapti** [comment]
I see now that the image has been updated, but I can still submit a PR if you'd like.

**Comment by epoberezkin** [comment]
yes, it would be helpful I think. Thank you!

**Comment by shumvgolove** [comment]
Hey @samsapti , I'm the maintainer of Docker images 👋

Currently, I'm working on setting up both `xftp-server` and `smp-server` (to be renamed from `simplexmq`) in our Docker Hub repository and also setting up Github actions. To be honest, Github actions is such a convoluted system that it was easier for me to execute 3 commands on my local computer every now and then, than to figure it all out :^) Making a PR with automatic Github actions would be much appreciated!

**Comment by samsapti** [comment]
@shumvgolove sounds good. Just a question then:

Does SimpleXMQ follow SemVer? I'm thinking about making three tags for each version, `vX.Y.Z`, `vX.Y` and `vX`, such that server operators have the option to pin the version to either major, minor or pathch versions and have automatic updates for the first two cases via fx. Watchtower. SemVer ensures no breaking changes on minor and patch updates, making automatic updates safe.

**Comment by shumvgolove** [comment]
> Does SimpleXMQ follow SemVer?

Yep, `simplexmq` follows SemVer scheme.

> I'm thinking about making three tags for each version, vX.Y.Z, vX.Y and vX

Yeah, makes sense. Also, would you kindly document how we should set up Github repo (create `DOCKERHUB_TOKEN`, `DOCKERHUB_USERNAME` secrets, etc.) and adjust the .yml workflow for future releases (`XFTP` image isn't out yet) in the PR description?

**Comment by samsapti** [comment]
> Also, would you kindly document how we should set up Github repo (create `DOCKERHUB_TOKEN`, `DOCKERHUB_USERNAME` secrets, etc.) and adjust the .yml workflow for future releases (`XFTP` image isn't out yet) in the PR description?

Of course! 👍

**Comment by samsapti** [comment]
@shumvgolove do you expect XFTP to be built from this repository as well, or a seperate one?

**Comment by shumvgolove** [comment]
From the same 🙂

**Comment by shumvgolove** [comment]
https://github.com/simplex-chat/simplexmq/commit/4d96e3700cab62f9a1b132ff3193c7faf7dd183e
