### ISSUE TITLE
Error starting the systemd xftp-server on Ubuntu 22.04

### ISSUE THREAD

**Issue by nicfab** [simplex-chat/simplexmq#766]
On Ubuntu server 22.04, I installed firstly the SMP service and then the XFTP one, following the instructions published on https://simplex.chat/docs

Regarding XFTP, I followed the instructions here: https://simplex.chat/docs/xftp-server.html 
I ran the `init` command in the following format `sudo su xftp -c "xftp-server init -l --fqdn mydomain -q '20gb' -p /srv/xftp/"`, and it seemed all ok.
I created the systemd file by pasting what is at point 5 here https://simplex.chat/docs/xftp-server.html

When I run sudo `systemctl start xftp-server.service` I receive an error, and running `systemctl status xftp-server.service` I see the following:

```
○ xftp-server.service - XFTP server systemd service
     Loaded: bad-setting (Reason: Unit xftp-server.service has a bad unit file setting.)
     Active: inactive (dead) since Sun 2023-06-04 16:34:28 CEST; 19min ago
   Main PID: 1027086 (code=killed, signal=TERM)
        CPU: 50ms

Jun 04 16:33:41 vps-fe63ca00 xftp-server[1027086]: [INFO 2023-06-04 16:33:41 +0200 src/Simplex/FileTransfer/Server/Env.hs:88] Total / available storage: 21474836480 / 21474836480
Jun 04 16:33:42 vps-fe63ca00 xftp-server[1027086]: [INFO 2023-06-04 16:33:41 +0200 src/Simplex/Messaging/Transport/Server.hs:87] binding to [::]:5443
Jun 04 16:33:49 vps-fe63ca00 systemd[1]: /etc/systemd/system/xftp-server.service:9: Failed to resolve unit specifiers in [ -e "/var/opt/simplex-xftp/file-server-store.log" ] && cp "/var/opt/simplex-x>
Jun 04 16:33:49 vps-fe63ca00 systemd[1]: xftp-server.service: Unit configuration has fatal error, unit will not be started.
Jun 04 16:34:28 vps-fe63ca00 systemd[1]: Stopping XFTP server systemd service...
Jun 04 16:34:28 vps-fe63ca00 xftp-server[1027086]:
Jun 04 16:34:28 vps-fe63ca00 systemd[1]: xftp-server.service: Deactivated successfully.
Jun 04 16:34:28 vps-fe63ca00 systemd[1]: Stopped XFTP server systemd service.
Jun 04 16:41:22 vps-fe63ca00 systemd[1]: /etc/systemd/system/xftp-server.service:9: Failed to resolve unit specifiers in [ -e "/var/opt/simplex-xftp/file-server-store.log" ] && cp "/var/opt/simplex-x>
Jun 04 16:41:22 vps-fe63ca00 systemd[1]: xftp-server.service: Unit configuration has fatal error, unit will not be started.

```

However, if I run `sudo su xftp -c "xftp-server start"` the server starts and I see the following:

```
[INFO 2023-06-04 17:09:13 +0200 src/Simplex/FileTransfer/Server/Env.hs:88] Total / available storage: 21474836480 / 21474836480
[INFO 2023-06-04 17:09:13 +0200 src/Simplex/Messaging/Transport/Server.hs:87] binding to [::]:port
```
I removed the port number for security reasons.

From the systemd side, if I edit the systemd file and comment the row `ExecStopPost=/usr/bin/env sh -c '[ -e "/var/opt/simplex-xftp/file-server-store.log" ] && cp "/var/opt/simplex-xftp/file-server-store.log" "/var/opt/simplex-xftp/file-server-store.log.$(date +'%FT%T')"'` it works fine.

I tested the xftp address on the app, and the result is Ok.
I have some doubts related to that systemd row I commented on.

I appreciate any help you can provide.

**Comment by ludetie** [comment]
Hello,

I had the same issue and find the solution ; the systemd unit needs two "%" in :
ExecStopPost=/usr/bin/env sh -c '[ -e "/var/opt/simplex-xftp/file-server-store.log" ] && cp "/var/opt/simplex-xftp/file-server-store.log" "/var/opt/simplex-xftp/file-server-store.log.$(date +'%%FT%%T')"'
to be accepted by systemd.

The doc needs to be corrected here : "https://simplex.chat/docs/xftp-server.html"

Regards,

**Comment by nicfab** [comment]
> Hello,
> 
> I had the same issue and find the solution ; the systemd unit needs two "%" in : ExecStopPost=/usr/bin/env sh -c '[ -e "/var/opt/simplex-xftp/file-server-store.log" ] && cp "/var/opt/simplex-xftp/file-server-store.log" "/var/opt/simplex-xftp/file-server-store.log.$(date +'%%FT%%T')"' to be accepted by systemd.
> 
> The doc needs to be corrected here : "https://simplex.chat/docs/xftp-server.html"
> 
> Regards,

Thank you very much.
It works fine now.
