### ISSUE TITLE
xftp-ubuntu-20_04-x86-64 recv , cannot specify the xftp server (-s option missing).

### ISSUE THREAD

**Issue by ludetie** [simplex-chat/simplexmq#768]
Hello,

With the command "xftp-ubuntu-20_04-x86-64 send", we can send specify the xftp server with -s option but with the command "xftp-ubuntu-20_04-x86-64 recv", we cannot:

ludeti@FiercePC:~/Apps$ ./xftp-ubuntu-20_04-x86-64 recv --help
Usage: xftp-ubuntu-20_04-x86-64 recv FILE [DIR] [-r|--retry RETRY] [--tmp TMP]
                                     [-v|--verbose] [-y|--yes]
  Receive file

Available options:
  FILE                     File description file
  DIR                      Directory to save file (default: system Downloads
                           directory)
  -r,--retry RETRY         Number of network retries (default: 3)
  --tmp TMP                Directory for temporary encrypted file (default:
                           system temp directory)
  -v,--verbose             Verbose output
  -y,--yes                 Yes to questions
  -h,--help                Show this help text
ludeti@FiercePC:~/Apps$ ./xftp-ubuntu-20_04-x86-64 send --help
Usage: xftp-ubuntu-20_04-x86-64 send FILE [DIR] [-n COUNT] [-s|--servers SERVER]
                                     [-r|--retry RETRY] [--tmp TMP]
                                     [-v|--verbose]
  Send file

Available options:
  FILE                     File to send
  DIR                      Directory to save file descriptions (default: current
                           directory)
  -n COUNT                 Number of recipients (default: 1)
  -s,--servers SERVER      Semicolon-separated list of XFTP server(s) to use
                           (each server can have more than one hostname)
  -r,--retry RETRY         Number of network retries (default: 3)
  --tmp TMP                Directory for temporary encrypted file (default:
                           system temp directory)
  -v,--verbose             Verbose output
  -h,--help                Show this help text

Regards,

**Comment by epoberezkin** [comment]
When you receive the file, you use the servers specified in the file description - they are the same servers the sender used to upload them to.
