### ISSUE TITLE
Question: many old "smp-server-store.log" files - safe to delete?

### ISSUE THREAD

**Issue by RainrZufall** [simplex-chat/simplexmq#860]
Hi,

Since I create a backup of my server every night and shut down the server to do this, "smp-server-store.log.*" files are created daily.

![smp-server-store logs](https://github.com/simplex-chat/simplexmq/assets/116357136/4a884b61-893b-4889-8c46-bb458857009f)

- What do these files contain and why are they necessary?
- Can these files be deleted without causing problems?
- Do the files have an impact on performance if a large number of them have accumulated?

Many thanks for your help.

**Comment by shumvgolove** [comment]
@RainrZufall 👋

> What do these files contain and why are they necessary?

These files contain user queues (for example queue 123 should pass messages to queue 456, etc.) and necessary for the server operation. Each time you restart your server, `smp-server-store.log` backs up with date appended, so in case of server incident you can recover your previous server state.

> Can these files be deleted without causing problems?

Files **with appended date** can be safely deleted, but you should at least keep the three (or any other quantity (even one) based on your confidence 🙂) most recent backups just to be safe.

> Do the files have an impact on performance if a large number of them have accumulated?

Nope, server reads just `smp-server-store.log`. These files only for the safety precautions.

**Comment by RainrZufall** [comment]
Many Thanks 👍
