### ISSUE TITLE
Restructure repos

### ISSUE THREAD

**Issue by epoberezkin** [simplex-chat/simplexmq#97]
- [ ] ~~Protocol name. SMP or SMQ?~~
- [x] rename repo simplex-messaging -> SimplexMQ
- [x] publish hackage lib
- [x] move dog-food to protocol repo
- [x] rename repo protocol -> chat
- [x] move protocol docs to SimplexMQ

**Comment by efim-poberezkin** [comment]
rename organization into simplex-org?
